### ISSUE TITLE
Botswana Facility Coordinate Audit

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#1]
- [x] Addfacility file to a new project 
- [x]   Do a definition query for the OU of interest using Level3name OU and export to a new file
- [x]   Add admin level of analysis shp, most likely PSNU. **Note in this ticket what shp was used by adding a comment,** including its file name
- [x]   Follow SQUAD instructions per below:
 
![image](https://user-images.githubusercontent.com/11572993/47922821-58b85d80-de8e-11e8-9a5f-1f05f4691329.png)

- [ ]   Save results of SQUAD run as an Excel file following this naming convention OU_FacilityAudit_2018MMDD
- [ ]   Put output in [spatial data management folder > November Facility Coordinate Audit](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FProjects%2FSpatial%20Data%20Management%2FNovember%20Facility%20Coordinate%20Audit&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D)

****If you encounter an error** in the tool, note the error here and tag the issue with the bug label.**

**Comment by NateHeard** [comment]
Used Botswana_PROD_5_District_HealthDistrictLsib_2018_Jan.shp. Encountered error: local variable 'longLat' referenced before assignment.

**Comment by NateHeard** [comment]
@gsarfaty 

QGIS 3.4.1 'Madeira' also returns an error, possibly more informative than 2.18: 

Checking for anomalies...
Saving results...
Traceback (most recent call last):
File "C:/Users/nate_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\squad-plugin-qgis3\squad_tool_algorithm.py", line 243, in processAlgorithm
analysis.execute(context, feedback)
File "C:/Users/nate_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\squad-plugin-qgis3\squad_analysis.py", line 208, in execute
self.writeOutput()
File "C:/Users/nate_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\squad-plugin-qgis3\squad_analysis.py", line 183, in writeOutput
if longLat in self.anomalies3:
UnboundLocalError: local variable 'longLat' referenced before assignment

Execution failed after 2.17 seconds

**Comment by NateHeard** [comment]
Identified and corrected topology errors. Fixed topology errors and received the same SQUAD error. Problem might not be related to topology.

**Comment by gsarfaty** [comment]
Thanks for checking 3.0 and topology. The more detailed log above might help them resolve the issue.

**Comment by gsarfaty** [comment]
Completed in ArcGIS using Botswana_PROD_5_District_HealthDistrictLsib_2018_Nov
