### ISSUE TITLE
Rwanda polygon completeness review

### ISSUE THREAD

**Issue by CmdrKerfy** [ICPI/GIS#117]
Based on the 2020 SQUAD analysis, the following adjusts were made to the Sector (level 6) DATIM metadata:

* **Add ' Sector' to the end of each admin**
--
* Busasamana(Nyanza) --> Busasamana Sector (Nyanza District)
* Busasamana(Rubavu) --> Busasamana Sector (Rubavu District)
* Cyanika(Burera) --> Cyanika Sector (Burera District)
* Cyanika(Nyamagabe) --> Cyanika Sector (Nyamagabe District)
* Kageyo(Gatsibo) --> Kageyo Sector (Gatsibo District)
* Kageyo(Gicumbi) --> Kageyo Sector (Gicumbi District)
* Kageyo(Ngororero) --> Kageyo Sector (Ngororero District)
* Karama(Huye) --> Karama Sector (Huye District)
* Karama(Kamonyi) --> Karama Sector (Kamonyi District)
* Karama(Nyagatare) --> Karama Sector (Nyagatare District)
* Kibilizi(Nyanza) --> Kibilizi Sector
* Kibirizi(Nyamagabe) [ Nyamagabe ] --> Kibirizi Sector (Nyamagabe District)
* Kibirizi(Nyamagabe) [ Gisagara ] --> Kibirizi Sector (Gisagara District)
* Kigarama [ Kicukiro ] --> Kigarama Sector (Kicukiro District)
* Kigarama [ Kirehe ] --> Kigarama Sector (Kirehe District)
* Kigoma(Huye) --> Kigoma Sector (Huye District)
* Kigoma(Nyanza) --> Kigoma Sector (Nyanza District)
* Kinazi [ Huye ] --> Kinazi Sector (Huye District)
* Kinihira(Ruhango) --> Kinihira Sector (Ruhango District)
* Kinihira(Rulindo) --> Kinihira Sector (Rulindo District)
* Mbazi(Huye) --> Mbazi Sector (Huye District)
* Mbazi(Nyamagabe) --> Mbazi Sector (Nyamagabe District)
* Muganza(Gisagara) --> Muganza Sector (Gisagara District)
* Muganza(Nyaruguru) --> Muganza Sector (Nyaruguru District)
* Muganza(Rusizi) --> Muganza Sector (Rusizi District)
* Mukarange(Gicumbi) --> Mukarange Sector (Gicumbi District)
* Mukarange(Kayonza) --> Mukarange Sector (Kayonza District)
* Muko(Gicumbi) --> Muko Sector (Gicumbi District)
* Muko(Musanze) --> Muko Sector (Musanze District)
* Mukura(Huye) --> Muko Sector (Huye District)
* Mukura(Rutsiro) --> Mukura Sector (Rutsiro District)
* Murama [ Kayonza ] --> Murama Sector
* Murama [ Ngoma ] --> Murama Sector (Ngoma District) 
* Murambi(Gatsibo) --> Murambi Sector (Gatsibo District)
* Murambi(Karongi) --> Murambi Sector (Karongi District)
* Murambi(Rulindo) --> Murambi Sector (Rulindo District)
* Murundi(Karongi) --> Murundi Sector (Karongi District)
* Murundi(Kayonza) --> Murundi Sector (Kayonza District)
* Musha(Gisagara) --> Musha Sector (Gisagara District)
* Musha(Rwamagana) --> Musha Sector (Rwamagana District)
* Nemba(Burera) --> Nemba Sector (Burera District)
* Nemba(Gakenke) --> Nemba Sector (Gakenke District)
* Ngoma(Huye) --> Ngoma Sector (Huye District)
* Ngoma(Nyaruguru) --> Ngoma Sector (Nyaruguru District)
* Ngoma(Rulindo) --> Ngoma Sector (Rulindo District)
* Nyagisozi(Nyanza) --> Nyagisozi Sector (Nyanza District)
* Nyagisozi(Nyaruguru) --> Nyagisozi Sector (Nyaruguru District)
* Nyamiyaga(Gicumbi) --> Nyamiyaga Sector (Gicumbi District)
* Nyamiyaga(Kamonyi) --> Nyamiyaga Sector (Kamonyi District)
* Nyarugenge(Nyarugenge) --> Nyarugenge Sector
* Nyange(Musanze) --> Nyange Sector (Musanze District)
* Nyange(Ngororero) --> Nyange Sector (Ngororero District)
* Nyarugenge(Bugesera) --> Nyarugenge Sector (Bugesera District)
* Nyarugenge(Nyarugenge) --> Nyange Sector (Ngororero District)
* Remera(Gasabo) --> Remera Sector (Gasabo District)
* Remera(Gatsibo) --> Remera Sector (Gatsibo District)
* Remera(Musanze) --> Remera Sector (Musanze District)
* Remera(Ngoma) --> Remera Sector (Ngoma District)
* Rugarama [ Gatsibo ] --> Rugarama Sector (Gatsibo District)
* Rugarama [ Burera ] --> Rugarama Sector (Burera District)
* Ruhango(Ruhango) --> Ruhango Sector (Ruhango District)
* Ruhango(Rutsiro) --> Ruhango Sector (Rutsiro District)
* Rukomo(Gicumbi) --> Rukomo Sector (Gicumbi District)
* Rukomo(Nyagatare) --> Rukomo Sector (Nyagatare District)
* Rwimbogo(Gatsibo) --> Rwimbogo Sector (Gatsibo District)
* Rwimbogo(Rusizi) --> Rwimbogo Sector (Rusizi District)
* Tumba(Huye) --> Tumba Sector (Huye District)
* Tumba(Rulindo) --> Tumba Sector (Rulindo District)

**_At this time DATIM Sector topology is up to date_**

**Comment by NateHeard** [comment]
Shapefile attribute data is up to date on AGOL.
