### ISSUE TITLE
Missing Geometry: Brazil

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#127]
We are missing the OU level boundary for Brazil in DATIM

When you add all boundaries for all countries in the Americas it appears, but it as part of a larger "Western Hemisphere" file, but it cannot be called on it's own.

**Comment by NateHeard** [comment]
Brazil's uid in the Western Hemisphere Level 4 file was erroneously the "world" uid. Brazil now has the correct uid on AGOL in an updated WesternHemisphere_PROD_4_National_NationalLsib_2022_Feb file. When this file is loaded to DATIM, we'll be able to close this ticket.
