### ISSUE TITLE
Missing Geometry: Burkina Faso

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#130]
The Missing Geometry query indicates that DATIM is missing 10 regions (level 5) and 26 provinces (level 6) that lack geometry. Based on a shapefile present in AGOL, level 7 in DATIM should be communes and facilities should be moved to level 8. This ticket tracks the effort to improve the completeness of Burkina Faso's map.

**Comment by NateHeard** [comment]
Layers in AGOL are mislabeled and lack uid altogether. I've removed these layers from AGOL and will reload with uid and a corrected name (BurkinaFaso_PROD_5_RegionsLsib_2022_Mar; BurkinaFaso_PROD_6_ProvincesLsib_2022_Mar).

**Comment by NateHeard** [comment]
Layers are loaded to AGOL. Next step it to load to DATIM.

**Comment by NateHeard** [comment]
Levels 5 and 6 are now loaded to DATIM.
