### ISSUE TITLE
Missing Geometry: China

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#135]
The Missing Geometry query indicates that DATIM contains 5 prefecture (level 6) and 48 counties (level 7) that lack geometry. This ticket tracks the effort to improve the completeness of China's map.

Currently China is only available in AGOL as part of the larger Asia region files. Might be helpful to parse these out so folks can call in just China.

**Comment by NateHeard** [comment]
China is not currently PEPFAR supported. Although of interest for mapping historical data, the country is not currently reporting.
