### ISSUE TITLE
Missing Geometry: DRC

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#138]
The Missing Geometry query indicates that DATIM contains 2 Health Zones that lack geometry. This ticket tracks the effort to improve the completeness of DRC's map at Level 5.

**Comment by NateHeard** [comment]
There is a Makiso at level 5 and at level 6. There is also a Makiso Kisangani at level 5, for which there is a matching uid. Neither "Makiso" have units below them in the hierarchy. Similarly, there is an unmatched Kingabwa 1 but there is also a Kingabwa, which does have a match. Makiso and Kingabwa 1 may be duplicates.
