### ISSUE TITLE
Missing Geometry: Kenya

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#139]
The Missing Geometry query indicates that DATIM contains 2 countries, 305 subcounties (Level 5), and 14777 wards (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of Kenya's map.

**Comment by NateHeard** [comment]
There is a sub county layer available via UNAIDS that is a good match for level 5. I'm reviewing this file and will test for loading to DATIM.

**Comment by NateHeard** [comment]
There are two level 5 units in DATIM that do not match the shapefile (Nakuru West Sub County and Rogena ward) and three subcounties in the shapefile that do not match DATIM (East Pokot, Kalama Sub County, and Kutulo Sub County). Level 5 is now present in Panorama, DATIM, and AGOL. The 1,477 wards are, to my knowledge, not mappable are the current time so I am closing this ticket.
