### ISSUE TITLE
Ukraine Team has requested a map showing prevalence by rayon in Chernihiv oblast and Facility Type

### ISSUE THREAD

**Issue by dp1984** [ICPI/GIS#14]
Ukraine team has provided data for maps. I'll make the data "pretty". & generate maps

**Comment by dp1984** [comment]
Uploaded map draft [here ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FWorking%20Folder%2FAd%20Hoc%2FUkraine&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D)& sent to Bob Gern for review. Will close if Bob has no further reviews/comments

**Comment by dp1984** [comment]
Bob Gern had no further edits/feedback

**Comment by gsarfaty** [comment]
@jltobias can you note the name of the boundary file you used? Then I will close the ticket. Thanks!
