### ISSUE TITLE
Missing Geometry: Ethiopia

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#143]
The Missing Geometry query indicates that DATIM contains 35 Woreda (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of Ethiopia's map at Level 6.

**Comment by NateHeard** [comment]
It's not uncommon for Ethiopia woreda, as used by the health sector, to lack official demarcation at the time of their creation. The PEPFAR Ethiopia team makes every effort to communicate information about demarcations as they become available. For this reason, there is currently no action to take here.
