### ISSUE TITLE
Missing Geometry: Ghana

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#144]
The Missing Geometry query indicates that DATIM contains 6 regions (Level 5), 45 districts (Level 6), 371 councils (Level 7) that lack geometry. This ticket tracks the effort to improve the completeness of Ghana's map.

**Comment by NateHeard** [comment]
An HDX file, sourced to the Ghana Statistical Services (GSS) matches DATIM's regions and districts perfectly.

**Comment by NateHeard** [comment]
Loaded to DATIM and AGOL.
