### ISSUE TITLE
Missing Geometry: Liberia

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#155]
The Missing Geometry query indicates that DATIM contains 4 (Level 5) and 12 (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of Liberia's map.

**Comment by NateHeard** [comment]
The level 5 units have matches and are now stored in Liberia_PROD_5_CountiesLsib_2022_Mar. Opportunities for Level 6 matches are not as clean. Several new, missing districts have matches. However, several do not, for example Buchanan, Bushrod, Saclepea-Mah, Somalia Drive. An updated shapefile that includes new matches is stored as Liberia_PROD_6_DistrictsLsib_2022_Mar.

**Comment by NateHeard** [comment]
Available in DATIM and AGOL.
