### ISSUE TITLE
Missing Geometry: Mali

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#157]
The Missing Geometry query indicates that DATIM contains 3 regions (Level 5) and 14 cercles (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of Mali's map.

**Comment by NateHeard** [comment]
Selingue, at level 6, has no match in the commune file. Selingue appears to be a dam in Yanfolila Cercle, Baya Commune. All other cercle and commune units had clear matches.

**Comment by NateHeard** [comment]
These data are now loaded to DATIM.
