### ISSUE TITLE
Missing Geometry: Nigeria

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#161]
The Missing Geometry query indicates that DATIM contains 1 state (Level 4) and 3 local government areas (Level 5) that lack geometry. This ticket tracks the effort to improve the completeness of Nigeria's map.

**Comment by NateHeard** [comment]
The Level 4 unit is Obubra General Hospital. This is an error in the hierarchy. Although there is a Go Nafada (cxm2xKiIBud) in DATIM, Go Nafada-Bajoga (fgDvaz58q64) contains all of the Nafada health facilities. Similarly, there are two im Ezinihitte. The one that has "missing geometry" has no health facilities underneath it (IxeWi5YG9lE). Finally, Damagum in Yobe appears to be a town and might not be a LGA.
