### ISSUE TITLE
Missing Geometry: Peru

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#164]
The Missing Geometry query indicates that DATIM contains 1 (Level 4) and 1 (Level 5) that lack geometry. This ticket tracks the effort to improve the completeness of Peru's map. -- common names not provided in the DATIM_OU_Hierarchy_Common_Names_Guide

**Comment by NateHeard** [comment]
Peru is not represented in the current PEPFAR-supported World Map and may be a placeholder. The only subnational unit in Peru is Peru PSNU Placeholder. This OU should be revisited in the future.
