### ISSUE TITLE
Missing Geometry: Philippines

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#165]
The Missing Geometry query indicates that DATIM contains 1 (Level 4), 1 (Level 5), 1 (Level 6), 54 (Level 7) that lack geometry. This ticket tracks the effort to improve the completeness of the Philippines's map. -- common names not provided in the DATIM OU Hierarchy Common Names Guide

**Comment by NateHeard** [comment]
Philippines includes entities such as "Philippines PSNU Placeholder". Will investigate candidate maps for level 7.

**Comment by NateHeard** [comment]
A large proportion of Level 7 units do not have a match in the shapefiles we investigated.
