### ISSUE TITLE
Missing Geometry: Saint Lucia

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#167]
The Missing Geometry query indicates that DATIM contains 2 districts (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of Saint Lucia's map.

**Comment by NateHeard** [comment]
Saint Lucia has a Castries and Vieux Forte District at level 5. The units are duplicated at level 6. Saint Lucia has sub-district divisions and "Vieux Fort/Laborie Highway" is among them. However, the exact duplication of Castries and Vieux Forte at levels 5 and 6 suggest a possible error here.
