### ISSUE TITLE
Missing Geometry: Saint Vincent and the Grenadines

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#168]
The Missing Geometry query indicates that DATIM contains 1 capital (Level 6)  that lack geometry. This ticket tracks the effort to improve the completeness of St Vincent and the Grenadines's map.

**Comment by NateHeard** [comment]
Commonly available administrative boundaries for Saint Vincent and the Grenadines do not extend below the parish, which is level 5. DATIM has no missing geometry at level 5.
