### ISSUE TITLE
Missing Geometry: South Africa

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#171]
The Missing Geometry query indicates that DATIM contains 267 local municipalities (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of South Africa's map.

**Comment by NateHeard** [comment]
Even without the references to AGRIAIDS, DATIM has 256 units at this level, compared to the 242 in the best available shapefile of which I am aware, SouthAfrica_Subdistrict_UNAIDS_SPECTRUM_2020. The country team, which includes GIS specialists are aware of the challenges with mapping level 6, which includes both municipalities and health subdistricts. I believe it is that latter that have been difficult to map accurately.
