### ISSUE TITLE
Missing Geometry: South Sudan

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#172]
The Missing Geometry query indicates that DATIM contains 1 state (Level 4), 1 county (Level 5), 136 Payam (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of South Sudan's map.

**Comment by NateHeard** [comment]
Bangasu Payam exists at level 4, which is the state level, and level 6, which is the correct payam level. Level 6 also includes four hospitals and a primary health care center. Outreach to the South Sudan team, to alert them to these org hierarchy errors, may be advised. I will investigate potential payam maps.

**Comment by NateHeard** [comment]
There is not a promising payam map candidate. The one level 5 county that is not represented on the map is Akok County. Although I was able to find several references to this county, which appears to be in Upper Nile State, I was not able to locate a representation of the county boundaries. There are no obvious ways to improve this map, although outreach to the country team may be helpful, particularly to alert them to the presence of facilities located improperly at level 6.
