### ISSUE TITLE
Missing Geometry: Tanzania

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#175]
The Missing Geometry query indicates that DATIM contains 2 Regions (Level 4), 2 councils (Level 5) and 4860 wards (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of Tanzania's map.

**Comment by NateHeard** [comment]
The shapefiles for region and district levels now include Songwe Region and Magharibi B District. Both region and district levels have a unit named National, which do not appear to be either a region of district.

**Comment by NateHeard** [comment]
The files are now updated in DATIM and AGOL.
