### ISSUE TITLE
Missing Geometry: Thailand

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#176]
The Missing Geometry query indicates that DATIM contains 336 (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of Thailand's map.

**Comment by NateHeard** [comment]
DATIM holds 336 units at level 6. The best shapefile match is from the Royal Thai Survey Department, contributed to HDX by OCHA Regional Office for Asia and the Pacific (ROAP); https://data.humdata.org/dataset/cod-ab-tha. The file is saved as Thailand_PROD_6_District_2022_May.

35 units in DATIM are unmatched. In most cases unmatched units appeared twice in DATIM and were clearly duplicates of the same district. For instance, there is a Wangthonglang and a Wangtonglang or Bang Kapi and Bangkapi in DATIM. In these instances, preference was given to the unit that contained health facilities.

**Comment by NateHeard** [comment]
Loaded to DATIM and AGOL.
