### ISSUE TITLE
Missing Geometry: Trinidad and Tobago

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#178]
The Missing Geometry query indicates that DATIM contains 6 (Level 6), 11 (Level 7) and 46 (Level 8) that lack geometry. This ticket tracks the effort to improve the completeness of Trinidad and Tobago's map.

**Comment by NateHeard** [comment]
Level 5 corresponds to the municipality. I was unable to locate representation of sub-municipality demarcations. Level 8 includes three units named "San Fernando". I believe this map is as complete as we are currently able to make it.
