### ISSUE TITLE
Missing Geometry: Uganda

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#179]
The Missing Geometry query indicates that DATIM contains 1 district (Level 5) and 1671 subcounty (Level 6) that lack geometry. This ticket tracks the effort to improve the completeness of Uganda's map.

**Comment by NateHeard** [comment]
The missing district is Terego District, which the Ugandan Parliament approved and which went into effect in July 2020. I've identified the boundary of Terego District and added it to our file.

**Comment by NateHeard** [comment]
The new district file is in DATIM and on AGOL.
