### ISSUE TITLE
Missing Geometry: Ukraine

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#180]
The Missing Geometry query indicates that DATIM contains 80 Rayon (Level 5) that lack geometry. This ticket tracks the effort to improve the completeness of Ukraine's map.

**Comment by NateHeard** [comment]
I've downloaded Ukraine_PROD_5_Rayon_2020_Jan and started to identify where the new rayon uid may be linked to the existing map. The existing map has uid for 271/629 units at that level. Twelve of the eighty rayon that lack geometry are "Rayon TBD".

**Comment by NateHeard** [comment]
On reviewing a new download of the Ukraine hierarchy, it was apparent that a substantial org unit revision of rayon had taken place. A revised file, Ukraine_PROD_5_Rayon_2022_Mar, is now on AGOL and a GML file is being loaded to DATIM.
