### ISSUE TITLE
Missing Geometry: Vietnam

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#183]
The Missing Geometry query indicates that DATIM contains 1 province (Level 4) and 3 districts (Level 5) that lack geometry. This ticket tracks the effort to improve the completeness of Vietnam's map.

**Comment by NateHeard** [comment]
The Level 4 unit is named "TO_DELETE". Phu My appears twice in DATIM, once in Ba Ria-Vung Tau and once in Binh Dinh. The Binh Dinh instance is represented in DATIM, AGOL, and Panorama. Ba Ria-Vung Tau's Phu My was not identified in the map published by OCHA Regional Office for Asia and the Pacific (ROAP), which cites Government of Viet Nam as the source of the file. Further research into official policy for representing the other two districts is necessary.
