### ISSUE TITLE
Update OU Hierarchy Common Names Guide

### ISSUE THREAD

**Issue by cmkalman** [ICPI/GIS#184]
Once the DATIM boundaries have been updated, we will also need to update the hierarchy guide. https://datim.zendesk.com/hc/en-us/articles/4405100067988-Common-Names-for-DATIM-levels 

- [x] Columbia and it's levels will need to be 
- [x] Add commune's to Burkina Faso at Level 7 (?)
- [x] Add Philipines

**Comment by NateHeard** [comment]
- Colombia extends only to the department level.
- At DATIM Level 7, Burkina Faso's units have prefixes such as CM and CMU, which seem to be references to levels of the health system.
- Philippines has three subnational levels.
- It was possible to add named levels to Benin.

**Comment by NateHeard** [comment]
Update has been submitted to the DATIM Support Team for posting.
