### ISSUE TITLE
Create Geospatial Data Cluster SOW & Workplan

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#2]
Need to create for presentation to ICPI leads ~end of March

**Comment by gsarfaty** [comment]
Working document lives here: I[CPI > Clusters >Geospatial Data > Administration > Workplan](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FAdministration%2FWorkplan&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D). Tentative strategy meeting the week of the 19th with the Geospatial Data team.

**Comment by jb3436** [comment]
testing slack integration.

**Comment by gsarfaty** [comment]
Planning meeting scheduled for 3/22 with below agenda

1. Year in review
        a. Main accomplishments
        b. Gaps
        c. What should do more of? What should we do less of?
    2. High level SOW & work plan overview - opportunity for discussion, clarification, etc.
        a. Tie in year in review to work plan, add any missing areas of work as needed
    3. Flesh out roles and responsibilities
        a. Assign people to work plan activities as "responsible," "consulted," or "informed"
    4. Draft presentation to Leads

**Comment by gsarfaty** [comment]
Work plan was approved, with feedback. @ICPI/gis will review and provide responses to the feedback within ~2 weeks
