### ISSUE TITLE
Facility by Period analysis

### ISSUE THREAD

**Issue by abeagedew** [ICPI/GIS#25]
Create an output to show the facilities by OU that are reporting data across all reporting periods

**Comment by abeagedew** [comment]
Output posted here:  https://www.pepfar.net/OGAC-HQ/icpi/Products/ICPI%20Data%20Store/MER/DAQ%20data%20requests/20181106_facilityByPeriod.zip

**Comment by gsarfaty** [comment]
Hi, @abrahamagedewICPI: can you re-run now that Q4 data entry is closed and add facility prioritization??

cc @NateHeard

**Comment by gsarfaty** [comment]
Nate pulled this and updated so this is no longer needed.
