### ISSUE TITLE
Spatial Data Creation & Data Management Webinar

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#26]
Webinar idea/request from exchange w/TZ team about the updates to their district council shp - team is strong on spatial analytics but would appreciate help to strengthen their spatial data creation & data management skills.

**Comment by gsarfaty** [comment]
Potential dates per TZ team: late in the week of Dec 3rd or better the following week of Dec 10th.

**Comment by gsarfaty** [comment]
Potential ideas:
- [ ] checking topology and fixing topology errors
- [ ] national level boundary editing (ex. matching to LSIB)
- [ ] subnational unit boundary editing (ex. creating boundaries to match a reference source).
- [ ] folder & file management best practices

thoughts, @NateHeard ?

**Comment by gsarfaty** [comment]
TZ's POART call is Thurs, 12/13 so they may want the days preceding it left open for POART preparation. 

Wonder if the following week is too close to winter holidays? I think we should propose a few date/time options each of those weeks to see what they prefer.

**Comment by gsarfaty** [comment]
Scheduled for Mon. 12/17; Agenda to be sent to team for review and feedback week of 11/26

**Comment by NateHeard** [comment]
This is more than one hour of material.

**Draft agenda**
_Spatial Data Lifecycle (brief document overview)_
_Administrative unit (polygons)_
- checking topology and fixing topology errors
- national level boundary editing (ex. matching to LSIB)
- subnational unit boundary editing (ex. creating boundaries to match a reference source; country team - HQ relationship for updating DATIM)
- Polygon completeness report
- AGOL; folder & file management best practices

_Points_
- Facility level data report
- SQUAD (live demo?)
- How to manage/improve point data (prioritizing direct survey and updates to DATIM)

**Comment by gsarfaty** [comment]
Email was sent to TZ SI iSMEs, PPM, & Agency leads in advance for awareness.

Webinar was held 12/18.

AGENDA:
Spatial Data Lifecycle (very brief document overview)
Administrative unit (polygons)
checking topology and fixing topology errors 
national level boundary editing (ex. matching to LSIB) 
subnational unit boundary editing (ex. creating boundaries to match a reference source; country team - HQ relationship for updating DATIM) 
Polygon completeness report 
AGOL; folder & file management best practices

We will cover points in a subsequent webinar.

Draft materials are in our [working folder here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FWorking%20Folder%2FSpatial%20Data%20Management%2FSpatial%20Data%20Creation%20%26%20Management%20Webinar&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D). Once complete we will distribute to the TZ team and circulate more broadly for wider use among the program.

**Comment by gsarfaty** [comment]
Training doc has been added to the wiki [here](https://www.pepfar.net/sites/icpi/Shared%20Documents/Clusters/Geospatial%20Data/Projects/Spatial%20Data%20Management/Boundary%20Editing%20in%20QGIS_20181227_v1_1.pdf). Closing issue.
