### ISSUE TITLE
Pano Dossier Feedback and Tracking of Visual Crossing Implementation

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#27]
Assignees provided feedback to data strong on the dossier soft launch on 10/31.

GS feedback here focuses primarily on the geospatial aspects:

Overall, it's great to have more flexibility and control over the dashboards. Though the drawback, is that the multitude of options may overwhelm our more entry-level data users. Even for those on the data savvy end of the spectrum, learning how to configure properly will require some training. Some of my issues noted below, for example, may be as a result of not knowing exactly which buttons to toggle.

**Static Indicator Analysis Dossier**

Overall:

Countries are missing - is this intentional to reduce size and options for the sake of the soft release? Alphabetically, I don't see countries after Tanzania (Uganda, Ukraine, Vietnam, Zambia, Zimbabwe).
 

Geospatial Analysis Chapter

Enhancements:

Going to a layer and selecting "show details" allows for a data export that is DRASTICALLY improved over existing panorama exports.
Latent features give promise for the future - ex. ability to had drive time layers, etc.
Great that you can use the space to combine maps and other types of visuals
 

Drawbacks:

At default, maps are centered around Southern Africa which may not encompass the geographic area of the country selection;  User has to dig through controls to zoom the actual area of interest - not intuitive
Maps are difficult to configure which could be the result of using a new tool and non-intuitive controls
Formatting options appear to give you flexible options for configuring legends but when different colors are selected, they do not actually update on the map.
 

 

**Dynamic Indicator Analysis Dossier**

Overall:

Countries are missing, but it's a different set of countries than what was missing from the Static Indicator Dossier
Tried to load for a long time...never loaded with one country, at PSNU & facility levels, two indicator bundles selected, and agency breakdowns selected.
Reduced to one country, PSNU & facility levels, two indicator bundles, with NO agency breakdown and it finally loaded but took a significant amount of time that I think would be prohibitive to country teams.
 

Geospatial Analysis Chapter

Did not get a map to load when selecting PSNU & facility levels before running the dossier
Tried with just SNU1 and still get an error that no suitable data are found. Could be user error but seems something should load as default.
 

 

**Testing Visuals Dossier**

Overall:

Countries are missing - seem to be the same missing from static indicator analysis.
 

**Additional Disaggregates Dossier**

Overall:

Countries are missing - seem to be the same missing from static indicator analysis, and testing visuals.

**Comment by gsarfaty** [comment]
Recent exploration of VC & TA to other teams done by @imujawar. Per previous notes and emails, quick chatter and troubleshooting convos can be addressed via the existing #analytic-workspaces Slack channel. Curated content (tutorials, tips & tricks, considerations, etc.) will be housed on the GIS Wiki linked from the existing software and tools page: https://github.com/ICPI/GIS/wiki/Software-&-Tool

**Comment by gsarfaty** [comment]
@imujawar to get in touch w/Nicole C re: linked map filtering so we can get documentation together that shows how to set this up and add to pepfar.net and link to it from Wiki.

**Comment by gsarfaty** [comment]
Nicole shared her documentation. It has been uploaded [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FProjects%2FRoutine%20Analytics%20%26%20System%20Development%2FDATIM%20and%20Panorama&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D).

@SpaceForceOne working on additional documentation next week.

**Comment by NateHeard** [comment]
This issue bundled into https://github.com/ICPI/DIV/issues/157. Mapping Dossier handed over to datastrong for testing and roll out to PROD.
