### ISSUE TITLE
Rwanda request for support to create SDS maps for their COP18 submission

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#4]
Request from Rwanda PCO for SDS support. 

Working files will be housed here: [ICPI > Clusters > Geospatial Data > Working folder > Ad Hoc > Rwanda](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FWorking%20Folder%2FAd%20Hoc%2FRwanda&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D)

@ICPI/gis

**Comment by dp1984** [comment]
I'll do these tomorrow (3/13) and send for review

**Comment by dp1984** [comment]
Posted this map set [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FProjects%2FAd%20Hoc%2FRwanda&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D): will send to Rwanda & GIS team for review

**Comment by dp1984** [comment]
sent updated mapset to Rwanda on 3/13 w/ updated labels
