### ISSUE TITLE
Burundi: Update Commune & Province Level Shapefiles

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#40]
As part of/follow up to #39:

PEPFAR Burundi Provincial shapefile, BurundiProvinceLsib2016May, is missing Rumonge Province. I created an updated provincial file for Burundi by assigning the following communes to Romonge Province:

Buyengero
Bugarama
Rumonge
Burambi
Muhuta

After assigning these to Romonge in the commune level shapefile, I dissolved on province name to create the updated provincial shp. I assigned DATIM uids to each province. This new shp is named BurundiProvinceLsib2019March.

**Comment by gsarfaty** [comment]
Need to:
- [x] add hierarchy to provincial shp & upload to AGOL
- [ ] check commune file and make any additional needed updates to UIDs, remove old hierarchy & add new, then upload to AGOL.

**Comment by gsarfaty** [comment]
New provincial file has been uploaded as pepfaradmin & shared to PEPFAR_ALL. The former provincial feature layer and shapefile have been marked as deprecated. 

Updates to commune file on hold as there are 18 with the name "TBD Commune."

**Comment by NateHeard** [comment]
Burma is updated as best we can make it. Agree on level 6 hold given that TDB Communes are present across multiple provinces.
