### ISSUE TITLE
Eswatini | Errant Coordinates - entered in wrong format

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#43]
18 facilities in Eswatini have coordinates entered in a format other than DD.

**Comment by gsarfaty** [comment]
We may wish to convert the coordinates in question:
https://www.pgc.umn.edu/apps/convert/

Gina & Nate to discuss coordinate pulls.

**Comment by NateHeard** [comment]
The 19 facilities with incorrectly formatted geographic coordinates now have empty latitude and longitude fields in DATIM. The country team should add coordinates in the correct format. However, this ticket may be closed.
