### ISSUE TITLE
Nigeria | Mapping urban footprint against facility tx_curr & tst_pos

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#44]
Initial request - map 8 high vol tx_curr & tst_pos sites in 2 states. Nate delivered.

Revised request - want to see curr and pos for all sites, not just the 8 and want to see which sites are urban v. rural. 

Gina prepped data, Nate added to existing layout and delivered to team.

**Comment by NateHeard** [comment]
Additional revisions provided 3/21. Nigeria team has delivered its outbrief. Ticket closed.
