### ISSUE TITLE
Uganda district update

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#49]
Uganda has added districts since the March 2018 shapefile update. New districts include Kwania, Bugweri, Kapelebyong, Kikuube, and Sembabule. I will verify updates with the country team and propose using boundaries in the UBOS file found here: https://data.humdata.org/dataset/uganda-administrative-boundaries-as-of-17-08-2018

**Comment by NateHeard** [comment]
The Uganda district file is now updated and loaded to ArcGIS Online. It will appear in the new Panorama map file, which is set for delivery to the Panorama Team on 7/12. DATIM gml/geoJSON import remains an issue.

**Comment by NateHeard** [comment]
Reopening. DATIM GML import now works and Uganda_PROD_5_District_DistrictLsib_2019_Jul should be loaded to DATIM. It is a perfect match for what is in DATIM. Note however, DATIM has 128 units and country has moved to 135.

**Comment by NateHeard** [comment]
Loaded to DATIM. In AGOL as Uganda_PROD_5_District_DistrictLsib_2019_Nov.

**Comment by CmdrKerfy** [comment]
Based on 2020 SQUAD analysis, Uganda districts should be updated once again.

**Comment by CmdrKerfy** [comment]
Initial draft of new Uganda district created based on this [OCHA shapefile](https://data.humdata.org/dataset/uganda-administrative-boundaries-admin-1-admin-3) from August 2020 and stored [HERE](https://pepfar.sharepoint.com/sites/ICPI/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=6pOlVc%2F&FolderCTID=0x012000DE0ED9A08616DD4AB01C9D14812A931300CD6F14A27D68D547B5474407F49FBAA5&viewid=b4298bef%2D654d%2D4935%2D9f4e%2D627716e0384a&id=%2Fsites%2FICPI%2FShared%20Documents%2FClusters%2FDAQ%2FGeospatial%20Data%2FProjects%2FSpatial%20Data%20Management%2FSQUAD%5F2020%5FSep%2FAdmin%5FShapefiles%20%5Btemp%5D) for review.

**Districts Added:**

- Kalaki District
- Karenga District
- Kazo District
- Kitagwenda District
- Madi-Okollo District
- Obongi District
- Rwampara District

_3 Districts were had boundaries edited to match the OCHA dataset as well_

**Comment by NateHeard** [comment]
In addition to the new boundaries, the new AGOL file, Uganda_PROD_5_District_DistrictLsib_2020_Feb, has includes many topolopogy error resolutions.
