### ISSUE TITLE
PEPFAR reference map for Burkina Faso

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#53]
The introduction of new countries to the DATIM and the COP Planning process requires the development of new maps for use in DATIM, Panorama, and ad hoc analysis.
 
1. Obtain DATIM OU hierarchy for Burkina Faso from the DATIM-Data-Import-and-Exchange-Resources page.
2. West Africa Region: https://www.datim.org/api/sqlViews/qyp2aXRK52d/data.csv?var=OU:WA
3. Identify lowest administrative unit level in the hierarchy.
4. Review candidate shapefiles for completeness of match to the hierarchy.
5. If unable to identify a perfect match contact DATIM Site Administrators with discrepancies (loop in @NateHeard).
6. Attach DATIM Extract with OrgUnit UIDs to matching shapefile.
7. Align international boundary to the World_PROD_3_World_Level3Lsib_2016_July layer
8. Derive higher administrative levels from lower LSIB-aligned file as needed.
9. Load files to AGOL as pepfaradmin using AGOL naming convention.

Note: The column with the uid must be named "uid".

**Comment by NateHeard** [comment]
foo

**Comment by CmdrKerfy** [comment]
HDX and GADM appear to have similar ADM3 names, with minor differences in topology. 

The HDX data, from USAID/ITOS, is noted as being a previous boundary data iteration, so there's a chance borders will need to be updated in the future. 

I'll default to using the ITOS data for the DATIM import.

**Comment by CmdrKerfy** [comment]
**Data Source:** HDX - OCHA Burkia Faso - ITOS
https://data.humdata.org/dataset/angola-administrative-levels-0-3

**Comment by CmdrKerfy** [comment]
**Data Notes:** None of the ADM2 (level5names) are actually provinces. The locations vary between cities and neighborhoods. There are no UIDs to match at this time for anything below Region level. See reference below:

| Name | Admin_Type | City | Province | Region |
| :------ | :------ | :------ | :------ | :------ |
| Baskuy | Arrondissement | Ouagadougou (National Capital) | Kadiogo | Centre |
| Boulmiougou | Arrondissement | Ouagadougou (National Capital) | Kadiogo | Centre |
| CMA 30 | *Likely a Health Facility* | N/A | Kadiogo | Centre |
| Nongr Massom | Arrondissement | Ouagadougou (National Capital) | Kadiogo | Centre |
| Signoghin | Arrondissement | Ouagadougou (National Capital) | Kadiogo | Centre |
| Koudougou | Provincial Capital | N/A | Boulkiemdé | Centre-Ouest |
| Reo | Provincial Capital | N/A | Sanguié | Centre-Ouest |
| Dafra | Arrondissement | *Likely Bobo-Dioulasso (Provincial Capital)* | Houet | Hauts-Bassins |
| Do | Arrondissement | *Likely Bobo-Dioulasso (Provincial Capital)* | Houet | Hauts-Bassins |
| Hounde | Provincial Capital | N/A | Tuy/Tui | Hauts-Bassins |

**Comment by CmdrKerfy** [comment]
Added to AGOL:

*BurkinaFaso_PROD_4_RegionsLsib_2020_Jan*
*BurkinaFaso_PROD_5_ProvincesLsib_2020_Jan*
*BurkinaFaso_PROD_6_DepartmentLsib_2020_Jan*

* GML file for PROD 4 Regions has been sent to Nate for review and DATIM import.

**Comment by NateHeard** [comment]
BurkinaFaso_PROD_4_RegionsLsib_2020_Jan had been loaded to DATIM and is queued for inclusion into the next Panorama update.
