### ISSUE TITLE
PEPFAR reference map for Nepal

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#54]
The introduction of new countries to the DATIM and the COP Planning process requires the development of new maps for use in DATIM, Panorama, and ad hoc analysis.

1. Obtain DATIM OU hierarchy for Nepal from the DATIM-Data-Import-and-Exchange-Resources page.
2. Asia Region: https://www.datim.org/api/sqlViews/qyp2aXRK52d/data.csv?var=OU:AA
3. Identify lowest administrative unit level in the hierarchy.
4. Review candidate shapefiles for completeness of match to the hierarchy.
5. If unable to identify a match contact DATIM Site Administrators with discrepancies (loop in @NateHeard).
6. Attach DATIM Extract with OrgUnit UIDs to matching shapefile.
7. Align international boundary to the World_PROD_3_World_Level3Lsib_2016_July layer
8. Derive higher administrative levels from lower LSIB-aligned file as needed.
9. Load files to AGOL as pepfaradmin using AGOL naming convention.

Note: The column with the uid must be named "uid".

**Comment by CmdrKerfy** [comment]
**Data Source:** HDX -- Housing recovery and reconstruction platform (HRRP) - Nepal. 

Government of Nepal data was also acquired but appears outdated and was not used.

**Comment by CmdrKerfy** [comment]
*Nepal_PROD_4_ProvincesLsib_2020_Jan* and *Nepal_PROD_5_DistrictLsib_2020_Jan* both added to AGOL and GML files shared with Nate for DATIM import.

**Comment by NateHeard** [comment]
Files successfully tested and then loaded to DATIM.
