### ISSUE TITLE
PEPFAR reference map for Liberia

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#55]
The introduction of new countries to the DATIM and the COP Planning process requires the development of new maps for use in DATIM, Panorama, and ad hoc analysis.

1. Obtain DATIM OU hierarchy for Liberia from the DATIM-Data-Import-and-Exchange-Resources page. West Africa Region: https://www.datim.org/api/sqlViews/qyp2aXRK52d/data.csv?var=OU:WA
2. Identify lowest administrative unit level in the hierarchy.
3. Review candidate shapefiles for completeness of match to the hierarchy.
4. If unable to identify a match contact DATIM Site Administrators with discrepancies (loop in @NateHeard).
5. Attach DATIM Extract with OrgUnit UIDs to matching shapefile.
6. Align international boundary to the World_PROD_3_World_Level3Lsib_2016_July layer
7. Derive higher administrative levels from lower LSIB-aligned file as needed.
8. Load files to AGOL as pepfaradmin using AGOL naming convention.

Note: The column with the uid must be named "uid".

**Comment by NateHeard** [comment]
Liberia_DRAFT_6_Lsib_2019_Oct.shp is LSIB aligned. The file now requires uid.

**Comment by CmdrKerfy** [comment]
**Data Source:** HDX - OCHA ROWCA

**Comment by CmdrKerfy** [comment]
**Data Management:** Inconsistent Admin Levels. The three following names from DATIM could not be found. All three appear to be within the *Greater Monrovia* District that does not currently have a UID. They could be admin 3 (Clans), data we do not currently have access to.

- Bushrod -- likely Bushrod Island located on the west coastal side of Greater Monrovia. 
- Somalia Drive -- A road that runs across Greater Monrovia.
- Central Monrovia -- Southwest tip of Greater Monrovia.

**Comment by CmdrKerfy** [comment]
**Data Management:** On final check, there appears to be some programming in _Grand Cape Mount County_ (ADM1), but no UID exists at this time.

**Comment by CmdrKerfy** [comment]
*Liberia_PROD_5_DistrictsLsib_2019_Oct* and *Liberia_PROD_4_CountiesLsib_2019_Oct* have been added to AGOL. Corresponding GML files have been sent to Nate for DATIM import.

**Comment by NateHeard** [comment]
Commonwealth (level 6), which is in Montserrado County in DATIM, shows up in a different county in the map source file (Grand Cape Mount). As @CmdrKerfy notes, Grand Cape Mount is not in DATIM.

**Comment by NateHeard** [comment]
Liberia_PROD_5_DistrictsLsib_2019_Oct contains two uid that DATIM does not recognize: lS9bsIteVth and VWMo5ZsdoJl. They do not appear to be in the system.

**Comment by NateHeard** [comment]
Liberia_PROD_5_DistrictsLsib_2019_Oct erroneously assigned Commonwealth in Montserrado to Grand Cape Mount. The shapefile also had extra spaces in the uid column. The file is now updated (Montserrado's was Commonwealth1 in shp) and saved under the same file name in AGOL. One unit, Bushwick, has no match. The program in Liberia only operates in Montserrado and all units in that area are accounted for and mapped. Districts are level 6 in the orgunit hierarchy. The name change was made to AGOL without updating the underlying zip file name. @CmdrKerfy can you fill out the metadata for this file on AGOL?

**Comment by NateHeard** [comment]
Similarly, Liberia_PROD_4_CountiesLsib_2019_Oct is level 5 in DATIM. Update made to name in AGOL. @CmdrKerfy, since you selected source shp and did vector editing, could you write metadata for this? Screenshot shows all three levels 4, 5, 6 in DATIM. 
![image](https://user-images.githubusercontent.com/13320367/79762393-b8a7fb80-82f0-11ea-87ce-91c725bab9a0.png)
