### ISSUE TITLE
PEPFAR reference map for Mali

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#56]
The introduction of new countries to the DATIM and the COP Planning process requires the development of new maps for use in DATIM, Panorama, and ad hoc analysis.

1. Obtain DATIM OU hierarchy for Mali from the DATIM-Data-Import-and-Exchange-Resources page. West Africa Region: https://www.datim.org/api/sqlViews/qyp2aXRK52d/data.csv?var=OU:WA
2. Identify lowest administrative unit level in the hierarchy.
3. Review candidate shapefiles for completeness of match to the hierarchy.
4. If unable to identify a match contact DATIM Site Administrators with discrepancies (loop in @NateHeard).
5. Attach DATIM Extract with OrgUnit UIDs to matching shapefile.
6. Align international boundary to the World_PROD_3_World_Level3Lsib_2016_July layer
7. Derive higher administrative levels from lower LSIB-aligned file as needed.
8. Load files to AGOL as pepfaradmin using AGOL naming convention.

Note: The column with the uid must be named "uid".

**Comment by NateHeard** [comment]
Mali_DRAFT_6_Lsib_2019_Oct.shp is LSIB aligned. The file now requires uid.

**Comment by CmdrKerfy** [comment]
**Data Source:** HDX -- OCHA Mali

**Comment by CmdrKerfy** [comment]
**Data Issues:** Admin 1 (Regions) appear to be missing. DATIM begins at Admin 2 (Cercles) and ends with Admin 3 (Communes).

- *Yanfolia* is a Cercle (ADM2) within *Sikasso Region* (ADM1), but mistakenly listed as a communue (ADM3) within *Sikasso Cercle* (ADM2).
- *Selingue Commune* does not appear to exist at any admin level and may be referring to the artificial lake. No UID added.

**Comment by CmdrKerfy** [comment]
**Data Issues:** On final check, it appears that duplicate names have caused issues with UIDs again. *Bamako Cercle* does not have a UID, but *Bamako Region* does. As such, the ADM2 *Bamako* will not be represented in the shapefile.

**Comment by CmdrKerfy** [comment]
*Mali_PROD_6_CommunesLsib_2019_Oct*, *Mali_PROD_5_CerclesLsib_2019_Oct*, and *Mali_PROD_4_RegionsLsib_2019_Oct* have been added to AGOL. The accompanying GML files have been sent to Nate for DATIM import.

**Comment by NateHeard** [comment]
bQjLesDl6Ob appears in both PROD_5 and PROD_6. If I read the hierarchy correctly, Level 4 should be the international border of Mali, which leaves a region (level 5) and commune (level 6) level below that. Then facilities.

**Comment by NateHeard** [comment]
Because West Africa is a regional program, Mali's national boundary is level 4. The regions are level 5. Level 6 is the cercles. The commune file on AGOL is not in the hierarchy, although some of those units share names with the cercles level. The hierarchy goes from level 6 to the facility. I've made an exception for Bamako, and promoted the communes to the cerles level.

**Comment by NateHeard** [comment]
Loaded to AGOL and DATIM.
![image](https://user-images.githubusercontent.com/13320367/80165530-a86e7580-85a9-11ea-8891-17780979a291.png)
