### ISSUE TITLE
Request for map from S. Sudan Team

### ISSUE THREAD

**Issue by dp1984** [ICPI/GIS#6]
email from S. Sudan team: 
"I am reaching out with a request. Earlier this month you provided us this map of sites (attached) along with the SSD parsed dataset.
We have made minor edits (four sites: two activated and two inactivated).
Attached file lists the changes (with color highlights) that has the corrected dataset in the tab “COP-18.
Additionally, I have inserted two columns: one for IM (Implementing mechanism) and one for Agency.

Request:
•	Is it possible to have sites/facilities plotted on the map, just like you did in the attached map, however, color code them differently i.e.
o	DOD – With a Square
o	USAID – With a Triangle
o	CDC – With a Circle
•	And THEN different colors for each of the IM (Implementing mechanism).
•	This will allow for us to see PEPFAR coverage by IM, by Agency and by type of county
•	Note that different colors for the facility dots, by type of county (Scale up aggressive vs. Sustained)) is not needed because the color density of the county (background) is indicative of whether the county is Scale up aggressive or sustained.

Lastly, we are just about to complete a country wide mapping of all HIV/AIDS sites including non-PEPFAR (Global Fund supported) sites. Once we do have that completed, we would like to figure out a possibility of mapping the non-PEPFAR sites (on this same map) and all of them could be just one color or type (no further disaggregation of those sites by implementing partner)."

**Comment by gsarfaty** [comment]
Two outputs sent to S. Sudan team and put in their folder here: [ICPI > Clusters > Geospatial Data > Projects > Ad Hoc > South Sudan](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FGeospatial%20Data%2FProjects%2FAd%20Hoc%2FSouth%20Sudan&View={94C838B2-E166-4122-B8B4-7BEB9E1BC12B}&InitialTabId=Ribbon%2ELibrary&VisibilityContext=WSSTabPersistence)

Will support the follow on of this request (mapping non-PEPFAR sites) if team has proper data to support it. Requirements for this were outlined in our email to them today, 4/2/18. Will close this ticket and open a new one if/when they have data for the country-wide mapping as it may be some time before that moves forward.

**Comment by NateHeard** [comment]
Used Swaziland_PROD_5_Tinkhundla_TinkhundlaLsib_2016_July.shp.
