### ISSUE TITLE
Zambia district update

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#60]
Imperial College has identified five districts in Spectrum list and MER, not in shape file:

- Luapula: Chifunabuli District [formerly Samfya district]
- Muchinga: Lavushi Manda District [formerly Mpika district]
- Northern: Lunte District [formerly Mporokoso District]
- NorthWestern: Kalumbila District [formerly Solwezi district]
- NorthWestern: Mushindano District [formerly Solwezi district]

**Comment by NateHeard** [comment]
Chifunabuli and Lunte Districts appear to be promoted constituencies. We can use old constituency boundaries to mark the new districts. We do not know how to demarcate the other three districts. I've reached out the the Zambia DATIM site administrators to see if they have guidance.

**Comment by NateHeard** [comment]
With assistance from UNAIDS, new districts were drawn and the resulting shapefile, Zambia_PROD_5_District_DistrictLsib_2019_Sep, matches DATIM. Four districts in Zambia are not in DATIM and include Kasenengwa District and Lusangazi District.

**Comment by NateHeard** [comment]
Kasenengwa District and Lusangazi District are present in DATIM. Zambia_PROD_5_District_DistrictLsib_2019_Sep will be updated and uploaded to DATIM.

**Comment by NateHeard** [comment]
Updated in DATIM.

**Comment by CmdrKerfy** [comment]
Based on latest SQUAD analysis, the following districts will be adjusted:

- Chiengi District --> **Chienge District**

- Chapangali District --> **Chipangali District**

- Ikeleng’i District --> **Ikelenge District**

- Kalumblia District --> **Kalumbila District**

- Kapiri Mposhi District --> **Kapiri-Mposhi District**

- Lusaka Urban District  --> **Lusaka District**

- Mushindano District --> **Mushindamo District**

- Senga Hill District --> **Senga District** 

- Shangombo District --> **Shang'ombo District**
