### ISSUE TITLE
Mozambique polygon completeness review 

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#63]
This issue tracks the review and update of the Mozambique map.

1. Download the most up-to-date shapefiles for the OU from AGOL.
2. Review DATIM polygon_datim_global and identify units that lack geometry. See PEPFAR SharePoint: HQ > ICPI > General > Clusters > Geospatial Data > Projects > Spatial Data Management > polygon_daitm_global.
3. Add uid to the attribute table where possible.
4. In the case of missing levels of geometry, identify possible matching shapfiles.
5. Document any potential problematic units (e.g. units at the wrong level; non-geogrpahic entities such as IPs) here.
6. Send updates shapefile to @NateHeard  and @gsarfaty for review and upload to AGOL, DATIM, and Panorama.

**Comment by jltobias** [comment]
Thanks Nate--- I will work on this for Mozambique and send to you and to Gina. - Jim

**Comment by jltobias** [comment]
Hi Nate and Gina:   My initial read on this is that the Mozambique Level 3 OU shapefile is fine (it has geometry and has uid and seems to be the standard polygon we expect).   The Mozambique Level 4 Province level shapefile seems fine too - except the name of the shapefile does not match the pattern of Level 3 & Level 5 (I was thinking to just save the Level 4 shapefile in the same naming convention as Level 3 & Level 5.     The Level 5 district shapefile appears to have the following issues:

1.  There are n=11 rows in the polygon_datim_global_level5 tab-delimited .tsv file that do not have geometries.   These are level5name = Derre, Doa, Larde, Liupo, Luabo, Macate, Mapai, Marara, Mocubela, Molumbo, Mulevala, Rapale, and Vanduzi.

Also --- there are n=2 polygons within the shapefile that are without matching uids in the .tsv file 
Those are level5name = Cidade De Nampula and level5name = Adm.

I checked the level5 shapefile for the n=11 within the .tsv file that have missing geometry.   It looks like our shapefile for level5 does not contain polygons for those n=11 in the .tsv that are missing geometries.   
I also checked the .tsv file for the n=2 polygons in the shapefile that do not have uids.
It seems that the .tsv file does not contain the level5name = Cidade De Nampula  nor the level5name = Adm.

I might need a better understanding of how to resolve / fix and might need your guidance.   Thank you -- Jim

**Comment by NateHeard** [comment]
Can you explore whether any official changes to Mozambique's districts could account for the eleven units? Are there any district maps in the usual repositories that contain any of these eleven districts? We should also see if there is a level below the district for which there may be maps. Sometimes administrative units are created at the wrong level (e.g. a ward could appear at the district level). We need to identify those cases as well. Our objective is a stronger map but also a cleaner and more accurate hierarchy.

**Comment by jltobias** [comment]
Hi Nate:   Thank you.  I will explore on Statoids and see if official changes could help explain.  Also -- I found this set of files on HDX:  https://data.humdata.org/dataset/mozambique-administrative-levels-0-3  and noticed that they have a polygon for Cidade De Nampula.    I wonder about the potential to explore other sources for missing geometries and perhaps cite those sources ?   I can imagine that Statoids might have history about whether districts split, merge, or are otherwise dropped or introduced....but then it still seems like we need some source for the new polygons unless it is some obviously described partition.   I also wondered about reaching out to Orrin and others on CDC Mozambique team to see if they have newer shapefiles that could help us.   Do these approaches help ?   Thank you also for thoughts about how sometimes that admin unit could appear at the wrong level in the hierarchy.   I will look again to see if I can get more information.    Thanks --Jim

**Comment by jltobias** [comment]
Hi Nate:  update to your point about recent changes in Mozambique districts.  The statoids site mentions that in 2013 --- 13 new districts were formed:
2013-03-21: Source [1] says that thirteen new districts were formed. 
Indeed ---these seem to be the n=11 that I am seeing in the .tsv file with blank geometries.
The statoid site lists these n=13
    1 -   Province = Manica      District = Macate
    2 -   Province = Manica      District = Vanduzi
    3 -   Province = Nampula   District = Mozambique Island
    4 -   Province = Nampula   District = Lurde
    5 -   Province = Nampula   District = Liupo
    6 -   Province = Tete   District = Doa
    7 -   Province = Tete   District = Marara
    8 -   Province = Zambezia   District = Derre
    9 -   Province = Zambezia   District = Luabo
  10 -   Province = Zambezia   District = Mocubela
  11 -   Province = Zambezia   District = Mulevala
  12 -   Province = Zambezia   District = Mulombo
  13 -   Province = Zambezia   District = Quelimane 

It sounds like the Portuguese is sometimes used for Mozambique Island....Ilha de Moçambique, which was listed as a district in both the 1997 and the 2007 census.

Jim

**Comment by jltobias** [comment]
I was initially excited about this NYU Mozambique District Shapefile from 2013:  https://geo.nyu.edu/catalog/stanford-vk927gs6011   but I'm not sure that it reflects the 13 new districts mentioned on the Statoids site.

**Comment by jltobias** [comment]
It looks like the HDX moz_admbnda_adm2_ine_20190607.shp file contained in the  https://data.humdata.org/dataset/mozambique-administrative-levels-0-3  zipfile ---has some of the polygons and geometries that we may need....

**Comment by NateHeard** [comment]
Reference file describes Rapale as Nampula. DATIM includes a Nampula and a Rapale, one of which may be a duplicate.

**Comment by NateHeard** [comment]
Cidade De Nampula has been retired and is now Nampula. Former Nampula is now Rapale. Shapefile is updated, loaded to AGOL, and map is loaded in DATIM.
