### ISSUE TITLE
Dominican Republic polygon completeness review 

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#68]
This issue tracks the review and update of the Dominican Republic map. Level 6 is unmapped. There are matches for each unit in the municipal file located here: https://data.humdata.org/dataset/dominican-republic-administrative-boundaries-levels-0-6 

1. Review DATIM polygon_datim_global and identify units that lack geometry. See PEPFAR SharePoint: HQ > ICPI > General > Clusters > Geospatial Data > Projects > Spatial Data Management > polygon_daitm_global.
2. Add uid to the attribute table where possible.
3. In the case of missing levels of geometry, identify possible matching shapefiles. Evaluate Oficina Nacional de Estadística for fitness.
4. Document any potential problematic units (e.g. units at the wrong level; non-geographic entities such as IPs) here.
5. Send updates shapefile(s) to Nate and Gina for review and upload to AGOL, DATIM, and Panorama.

**Comment by CmdrKerfy** [comment]
DATIM reported down to Level 6 (ADM3 - Municipalities). Missing *Esperanza* and *San Juan de la Maguana* in our dataset. 

UIDs added for all other named municipalities.

Level 4 names (ADM1 - Regions) don't appear to match the HDX dataset's information. This may lead to region level maps becoming inconsistent with provincial and municipal level map products.

**Comment by CmdrKerfy** [comment]
*DominicanRepublic_PROD_6_MunicipalityLsib_2020_Jan* added to AGOL and GML sent to Nate for review and DATIM import.

**Comment by NateHeard** [comment]
DominicanRepublic_PROD_6_MunicipalityLsib_2020_Jan uid error is now updated in AGOL. Layer is also present in DATIM and will be part of the next Visual Crossing update.
