### ISSUE TITLE
Namibia polygon completeness review 

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#72]
This issue tracks the review and update of the Namibia map. There are two health districts in the shapefile that require a uid from DATIM.

**Comment by NateHeard** [comment]
Namibia health facilities are organized in the 36 district configuration with one exception. The facilities that should be present in Nkurenkuru are assigned to Rundu. As a result, the current update (Namibia_PROD_5_District_DistrictLsib_2019_Dec) has 35 units and does not include Nkurenkuru. File is on AGOL and needs upload to DATIM.

**Comment by CmdrKerfy** [comment]
The Namibia team has sent me a stripped down shapefile with **38 districts**. Please note that I was often asked to rename *Lüderitz* district as *!Nami#nus* on map products.

I will review the country team's shared shapefile with UNAIDS geographic information for eventual DATIM update.

**Comment by CmdrKerfy** [comment]
Per country team's direction, I have switched back to the 2016 district dataset and depreciated the 2019 dataset in AGOL.

**Comment by NateHeard** [comment]
There are only 36 districts in DATIM. If the team has transitioned to the 38-district configuration the team can initiate an org unit hierarchy change. If Lüderitz district is actually named !Nami#nus, the DATIM Site Administrator should likely make this change in DATIM.
