### ISSUE TITLE
Zimbabwe district shapefile update

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#75]
DATIM will split Guruve into two districts i.e. Mbire and Guruve in line with MOH DHIS2 organizational hierarchy. DATIM will also divide Kadoma district into Sanyati District and Mhondoro District in line with MOH's DHIS2 organizational hierarchy. These two splits will subsequently bring their DATIM OU into alignment with what Zimbabwe MoH has provided UNAIDS, which is another objective from the Target setting team.

**Comment by NateHeard** [comment]
Checked DATIM on 12/5. The new districts do not yet appear there. No map action at this time.

**Comment by CmdrKerfy** [comment]
Still no districts on 1/22/20. Will check again next quarter.

**Comment by NateHeard** [comment]
DATIM now shows a divided Kadoma district into Sanyati District and Mhondoro District in line with MOH's DHIS2 organizational hierarchy. I will update this map and load a new file to AGOL and DATIM.

**Comment by NateHeard** [comment]
Districts updated. Topology cleaned. Loaded to AGOL and DATIM.
