### ISSUE TITLE
Zambia - District move to different province

### ISSUE THREAD

**Issue by gsarfaty** [ICPI/GIS#83]
Shibuyunji District is now under Central Province instead of Lusaka. Need to update hierarchy table in the district file and then punch out new provincial file. Hierarchy in DATIM has been revised Feb 2020 to reflect this change.

**Comment by NateHeard** [comment]
Geometry was correct. Update required change to name in attribute table. Took opportunity to close gaps and remove some overlaps. Update to file made to DATIM and AGOL.
