### ISSUE TITLE
GIS Content on DATIM Support

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#84]
This issue will track a review of GIS Content on DATIM Support, guidance on changes, and the development of replacement materials as necessary. 

Article | Action (Approve, Update, Archive)
-- | --
[GIS OU Hierarchy Guide](https://datim.zendesk.com/hc/en-us/articles/206855986-GIS-OU-Hierarchy-Guide) | Archive
[GIS Analytics Series](https://datim.zendesk.com/hc/en-us/articles/206276395-GIS-Analytics-Series) | Update (see notes below) 
[Video Tutorial - Geographic Information System (GIS)](https://datim.zendesk.com/hc/en-us/articles/205028629-Video-Tutorial-Geographic-Information-System-GIS-) | Archive page. Add link on this page to Trainer Guide page.
[Hands-on Exercise - Geography in DATIM (GIS)](https://datim.zendesk.com/hc/en-us/articles/204956595-Hands-on-Exercise-Geography-in-DATIM-GIS-) | Archive
[Trainer Guide - Geography in DATIM (GIS)](https://datim.zendesk.com/hc/en-us/articles/204416595-Trainer-Guide-Geography-in-DATIM-GIS-) | Approve this version. Similar document needed for current Map App
[DATIM GIS Supplement](https://datim.zendesk.com/hc/en-us/articles/204418755-DATIM-GIS-Supplement) |  Archive this version. Will prepare update: PEPFAR Spatial Data Lifecycle

**Comment by NateHeard** [comment]
The **GIS Analytic Series** recordings seem worth keeping for now. However, while the content is valid the series is out of date. It uses the older DATIM Map Module and has a pre-Panorama framing. The page requires this update: "Most recent version of the DATIM GIS Supplement" will be updated to "Most recent version of the PEPFAR Spatial Data Lifecycle." The other two links in the Supplementary information on the DATIM Support Site (at the bottom of the page) should be removed.

**Comment by NateHeard** [comment]
**PEPFAR Spatial Data Lifecycle** draft revision is complete and under review by GIS Team.

**Comment by NateHeard** [comment]
**Hands-on Exercise - Geography in DATIM (GIS)** is duplicative of what is in the **Trainer Guide - Geography in DATIM (GIS)**. Recommending that we archive it.

**Comment by paigeschoenberg** [comment]
Hi GIS Team - thanks so much for your efforts on this! I have made the updates according to the table. Please keep me posted on further updates that you'd like to make or any new articles you'd like to post and our team will make note of it in our tracker of all Zendesk content.

Updates 4/30/2020:

- Added this line, "Update April 2020: The most recent version of the DATIM GIS Supplement will be updated to the most recent version of the PEPFAR Spatial Data Lifecycle." to the bottom of the GIS Analytics Series article and removed the two article links below that.
- Archived the four articles as noted above. **Question:** Why do you want to add a link on Video Tutorial - GIS page to the Trainer Guide page if the Video Tutorial page is archived?

Best,
Paige

**Comment by NateHeard** [comment]
Hi @paigeschoenberg, thanks very much for making these updates. We are currently clearing the document that will eventually replace the GIS Supplement and will provide that to your team when it becomes available for public presentation. 

Regarding your question, I think the Video Tutorial page had a link at the bottom, something like an additional resource, that might have been relevant for the Trainer Guide page. So the note, "Add link on this page to Trainer Guide page." was a reference that, not the Video Tutorial page link or page itself. The Video Tutorial link no longer works and perhaps it wasn't that important anyway. But if the old Video Tutorial page is visible to you, the resource link at the bottom might be useful as an addition to the Trainer Guide page (if memory serves).
