### ISSUE TITLE
Wiki Content Review

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#86]
Semiannual review of wiki content and link integrity: https://github.com/ICPI/GIS/wiki

**Comment by gsarfaty** [comment]
Pages to review:

- [x] 1. Guidance Documents

- [x] 2. PEPFAR-specific Spatial Data Management & Related Resources

- [x] 3. Software & Tools

- [x] 4. Data Sources

- [x] 5. Training Resources

- [x] 6. Health Geography Research

**Comment by gsarfaty** [comment]
all pages have been updated for relevancy and link intergrity. feel free to suggest editions to the pages @ICPI/gis

**Comment by gsarfaty** [comment]
Hearing no calls for edits, closing the ticket.
