### ISSUE TITLE
[Pano Dev] TB Cluster Support

### ISSUE THREAD

**Issue by CmdrKerfy** [ICPI/GIS#88]
The TB cluster has identified three maps that they'd like to be added to the mapping dossier and potentially as standalone products, depending on the particular request.

**DATASET:** 
- Latest clean MSD (FY19Q4 at time of writing this)

**MAP 1:** 
- Indicator: TBPREV_NUM

**MAP 2:**
- Indicators: TBPREV_NUM Result / TBPREV_TOL NUM TARGETS

**MAP 3:**
- Indicators: TPTCOVERAGE TB PREV NUM / DEM

**MAP FORMAT:** 
- Along with these three maps, the cluster has requested that center points for the PSNUs should be used instead of health facilities. They would also like the ability to turn off/on the point data, otherwise we would likely have to remake the make without the point data in a separate page within the chapter.

**Comment by NateHeard** [comment]
This information will be added to the Planned Dossier Updates Template and submitted by COB Monday 5/18.

**Comment by NateHeard** [comment]
TB chapter and pages in Map Dossier now live in Pano.
