### ISSUE TITLE
South Africa: geographic coordinate review 

### ISSUE THREAD

**Issue by NateHeard** [ICPI/GIS#98]
- [x] Add facility file to a new project

- [x] Do a definition query for the OU of interest using Level3name OU and export to a new file

- [ ] Add admin level of analysis shp, most likely PSNU. **Note in this ticket what shp was used by adding a comment, including its file name**

- [ ] Follow SQUAD instructions, roughly, per below:
![image](https://user-images.githubusercontent.com/11572993/47923618-50612200-de90-11e8-94fc-779305d92f61.png)

- [ ] Save results of SQUAD run as an Excel file following this naming convention OuSquadOutputTable_2020_Sep

- [ ] Put output in [spatial data management folder > SQUAD_2020_Sep](https://www.pepfar.net/sites/icpi/Shared%20Documents/Clusters/Geospatial%20Data/Projects/Spatial%20Data%20Management/SQUAD_2020_Sep)

**If you encounter an error in the tool, note the error here and tag the issue with the bug label.**

**Comment by NateHeard** [comment]
FYI: @CmdrKerfy

**Comment by CmdrKerfy** [comment]
Updated link to new  [PEPFAR SP Site](https://pepfar.sharepoint.com/sites/ICPI/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=6pOlVc%2F&FolderCTID=0x012000DE0ED9A08616DD4AB01C9D14812A931300CD6F14A27D68D547B5474407F49FBAA5&id=%2Fsites%2FICPI%2FShared%20Documents%2FClusters%2FDAQ%2FGeospatial%20Data%2FProjects%2FSpatial%20Data%20Management%2FSQUAD%5F2020%5FSep&viewid=b4298bef%2D654d%2D4935%2D9f4e%2D627716e0384a) for uploading

**Comment by CmdrKerfy** [comment]
SQUAD exported table added to SharePoint using aforementioned updated SP link.
